zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: tdt-authenticate-service
    project:
      path: /project/**
      serviceId: tdt-project-service
    testplan:
      path: /plan/**
      serviceId: tdt-testplan-service
    version:
      path: /version/**
      serviceId: tdt-versionmgr-service
    web:
      path: /web/**
      serviceId: tdt-web-service
    synchronize:
      path: /sync/**
      serviceId: tdt-synchronize-service
    cloudtest:
      path: /cloudtest/**
      serviceId: tdt-cloudtest-data-service
