#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver  
#    url: jdbc:mysql://localhost:3306/tdt?characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456

#c3p0:
#  jdbcUrl: jdbc:mysql://localhost:3306/tdt?characterEncoding=utf8&useSSL=false
#  user: root
#  password: 123456
#  driverClass: com.mysql.jdbc.Driver

dbcp:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/tdt?characterEncoding=utf8&useSSL=false
  username: root
  password: 123456
  
spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
#    type: com.mchange.v2.c3p0.ComboPooledDataSource

#mybatis:
#  config-locations: classpath:mybatis-config.xml
