spring:
  application:
    name: tdt-testplan-service
# profiles:
#    active: eureka-dev
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
      
server:
  port: 8050
